
## GET PROPERTY
GET https://staybnb-server.onrender.com/property/

### GET USER

GET https://staybnb-server.onrender.com/users/

### REGISTER NEW USER

POST https://staybnb-server.onrender.com/register
Content-Type: application/json

{
  "email": "newEmail@email.com",
  "password": "bestPassw0rd",
  "firstname": "User",
  "lastname": "Stay",
  "country": "India",
  "favorite": [],
  "isAdmin": false
}

### Register test user

POST https://staybnb-server.onrender.com/register
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "12345678",
  "name": "Test User",
  "favorite": [],
  "isAdmin": false
}

### LOGIN REGISTERED USER

POST https://staybnb-server.onrender.com/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "adminPass@123"
}

### Wrong Password and email will give error which should handled gracefully

POST https://staybnb-server.onrender.com/login
Content-Type: application/json

{
  "email" : "IncorrectEmail@email.com",
  "password": "adminPass@123"
}

###

POST https://staybnb-server.onrender.com/login
Content-Type: application/json

{
  "email" : "admin@admin.com",
  "password": "Wrong Password"
}